import type { Metadata } from "next";
import "./globals.css";
import { HexagonBackground } from "@/components/ui/hexagon-background";
import { ThemeProvider } from "@/components/themeProvider";
import { QueryProvider } from "@/components/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Docify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-dvh w-full">
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <QueryProvider>
            <div className="relative">{children}</div>
            <Toaster />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
